image: golang:1.13

stages:
  - build
  - release

build:
  stage: build
  script:
    - 'ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""'
    - make
  artifacts:
    paths:
      - bin

release:
  stage: release
  script:
    - apt-get update && apt-get -y install file jq
    - scripts/make-release.sh
  only:
    - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
  except:
    - branches
