// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HostScanner is an autogenerated mock type for the HostScanner type
type HostScanner struct {
	mock.Mock
}

// ScanForAliveHosts provides a mock function with given fields: cidr
func (_m *HostScanner) ScanForAliveHosts(cidr string) (*[]string, error) {
	ret := _m.Called(cidr)

	var r0 *[]string
	if rf, ok := ret.Get(0).(func(string) *[]string); ok {
		r0 = rf(cidr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(cidr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
