// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/TheNatureOfSoftware/k3pi/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// InstallerFactories is an autogenerated mock type for the InstallerFactories type
type InstallerFactories struct {
	mock.Mock
}

// GetFactory provides a mock function with given fields: task
func (_m *InstallerFactories) GetFactory(task interface{}) model.InstallerFactory {
	ret := _m.Called(task)

	var r0 model.InstallerFactory
	if rf, ok := ret.Get(0).(func(interface{}) model.InstallerFactory); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.InstallerFactory)
		}
	}

	return r0
}
