// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/TheNatureOfSoftware/k3pi/pkg/model"
	mock "github.com/stretchr/testify/mock"
)

// RemoteAssetOwner is an autogenerated mock type for the RemoteAssetOwner type
type RemoteAssetOwner struct {
	mock.Mock
}

// GetRemoteAssets provides a mock function with given fields:
func (_m *RemoteAssetOwner) GetRemoteAssets() model.RemoteAssets {
	ret := _m.Called()

	var r0 model.RemoteAssets
	if rf, ok := ret.Get(0).(func() model.RemoteAssets); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.RemoteAssets)
		}
	}

	return r0
}
